#!/bin/bash

function mcsas-update {
   original=`cat newgui.py |grep fastmath.version | awk '{print $4}'`
   git pull origin master
   new=`cat newgui.py |grep fastmath.version | awk '{print $4}'`
   if [ $original != $new ]
      then
         make
   fi
}

while getopts "u" opt; do
   case $option in
      "u") mcsas-update;
   esac
done

python2.7 newgui.py
